server:
  port: 8090
  undertow:
    accesslog:
      enabled: true
      dir: undertow-log
      prefix: access_log
      pattern:  '[%{time,yyyy-MM-dd HH:mm:ss.S z}] %b %l %u %I %v %a %m %U %s (%D ms)'
      rotate: true
      suffix: .log
    buffer-size: 1024
    worker-threads: 20
    direct-buffers: true

logging:
  config: classpath:log4j2-testing.yml
  path: ./.log

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&jdbcCompliantTruncation=false&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 1800000
      connection-timeout: 30000
      read-only: false
      idle-timeout: 300000
      auto-commit: true
      connection-test-query: SELECT 1
      pool-name: HikariDataSource

  rabbitmq:
    host: 192.168.1.33
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisherConfirms: true
    cache:
      channel:
        size: 10
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 10

  # cache config
  cache:
    type: ehcache
    ehcache:
      config: classpath:cache/ehcache-dev.xml
  #  cache:
  #    # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
  #    type: redis

  redis:
    host: 192.168.1.113
    timeout: 30000
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    # database: 0
    port: 6379
    password: dreamwindows
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 2
        # 连接池中的最大空闲连接 默认 8
        max-wait: 5000ms
        # 连接池中的最小空闲连接 默认 0
        min-idle: 1

app-config:
  ding-url: https://oapi.dingtalk.com
